
import { v4 as uuidv4 } from 'uuid';

export const detailsFormObject: any = {
  employeeId: {
    id: uuidv4(),
    label: 'Employee ID',
    value: '',
    type: 'InputText',
    validations: [
      {
        required: 'Employee Code should not be blank',
        length:'Employee Code length should not be greater than 8 char '
      }
    ],
    disabled: false,
  },
  fullName: {
    id: uuidv4(),
    label: 'Full Name',
    value: '',
    type: 'InputText',
    validations: [],
    disabled: false,
  },
  empStatus: {
    id: uuidv4(),
    label: 'Employment Status',
    value: 'ACTIVE',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  firstName: {
    id: uuidv4(),
    label: 'First Name',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  lastName: {
    id: uuidv4(),
    label: 'Last Name',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  dob: {
    id: uuidv4(),
    label: 'Date of Birth',
    value: '',
    type: 'Date',
    validations: ['required'],
    disabled: false,
  },
  gender: {
    id: uuidv4(),
    label: 'Gender',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  maritalStatus: {
    id: uuidv4(),
    label: 'Marital Status',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  nationality: {
    id: uuidv4(),
    label: 'Nationality',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  phoneNumber: {
    id: uuidv4(),
    label: 'Phone Number',
    value: '',
    type: 'InputText',
    validations: ['required', 'pattern:^\\d{10}$'],
    disabled: false,
  },
  alternateNumber: {
    id: uuidv4(),
    label: 'Alternate Number',
    value: '',
    type: 'InputText',
    validations: ['pattern:^\\d{10}$'],
    disabled: false,
  },
  email: {
    id: uuidv4(),
    label: 'Email',
    value: '',
    type: 'InputText',
    validations: ['required', 'email'],
    disabled: false,
  },
  streetAddress: {
    id: uuidv4(),
    label: 'Street Address',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  city: {
    id: uuidv4(),
    label: 'City',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  state: {
    id: uuidv4(),
    label: 'State',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  zipCode: {
    id: uuidv4(),
    label: 'Zip Code',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  country: {
    id: uuidv4(),
    label: 'Country',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  role: {
    id: uuidv4(),
    label: 'Role',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  teamManager: {
    id: uuidv4(),
    label: 'Team Manager',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  projectManager: {
    id: uuidv4(),
    label: 'Project Manager',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  teamLead: {
    id: uuidv4(),
    label: 'Team Lead',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  jobTitle: {
    id: uuidv4(),
    label: 'Job Title',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  employmentStatus: {
    id: uuidv4(),
    label: 'Employment Status',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  joinedDate: {
    id: uuidv4(),
    label: 'Joined Date',
    value: '',
    type: 'Date',
    validations: ['required'],
    disabled: false,
  },
  skillset: {
    id: uuidv4(),
    label: 'Skillset',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  payGrade: {
    id: uuidv4(),
    label: 'Pay Grade',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  currency: {
    id: uuidv4(),
    label: 'Currency',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  basicSalary: {
    id: uuidv4(),
    label: 'Basic Salary',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
  payFrequency: {
    id: uuidv4(),
    label: 'Pay Frequency',
    value: '',
    type: 'InputText',
    validations: ['required'],
    disabled: false,
  },
};
